---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: s3
  template:
    metadata:
      labels:
        name: s3
      annotations:
        prometheus.io.scrape: "false"
    spec:
      containers:
      - name: minio
        image: minio/minio
        args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          value: "abc"
        - name: MINIO_SECRET_KEY
          value: "12345678"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: storage
          mountPath: "/storage"
      volumes:
      - name: storage
        emptyDir: {}
